import 'regenerator-runtime';
import './script/component/foot-er';
import './script/component/app-bar';
import './script/component/head-bar';
import 'bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap/dist/js/bootstrap.min.js';
import './styles/main.css';
import './styles/responsive.css';
import './script/view/main';
