import './script/component/foot-er'
import './script/component/app-bar'
import 'bootstrap/dist/css/bootstrap.min.css'
import 'bootstrap/dist/js/bootstrap.min.js'
import './styles/appBar-style/Brands.css'
import './styles/appBar-style/dh-navbar-centered-brand.css'
import './styles/footer-style/bottom.css'
import './styles/appBar-style/navigation.css'